spring.application.name=demo
spring.mongodb.uri=mongodb://localhost:27017/RestaurantDb
spring.mongodb.database=RestaurantDb
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
